// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    url: "http://127.0.0.1:5000"
  }
});

export default function() {
  postman[Request]({
    name: "Book Search",
    id: "7ec3ff3b-5da6-41ec-ba87-046aa0468331",
    method: "GET",
    address: "{{url}}/searchBook",
    data: '{\n\t"searchQuery":"{{book}}"\n}',
    pre() {
      var books = pm.environment.get("books");
      if (!books) {
        var all_books = [
          "To Kill A Mockingbird",
          "Harry Potter",
          "Agatha Christie",
          "The Mummy",
          "Inside Out",
          "Black Hole"
        ];
        books = all_books;
      }
      var currentBook = books.shift();
      pm.environment.set("book", currentBook);
      pm.environment.set("books", books);
    },
    post(response) {
      var books = pm.environment.get("books");
      pm.test("Response time is less than 300ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(300);
      });
      tests["Status code is not 500"] = responseCode.code != 500;
      if (books && books.length <= 0) {
        pm.environment.unset("books");
        pm.environment.unset("book");
      }
    }
  });

  postman[Request]({
    name: "Get Recommendation",
    id: "19ca55b6-b9b9-4093-860a-1569637703ed",
    method: "GET",
    address: "{{url}}/getRecommendation",
    data: '{\n\t"searchQuery":"ID00100{{req}}"\n}',
    pre() {
      var count = pm.environment.get("req_count");
      if (!count) {
        count = 0;
      }
      pm.environment.set("req", count % 5);
      pm.environment.set("req_count", count + 1);
    },
    post(response) {
      pm.test("Response time is less than 300ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(300);
      });
      tests["Status code is not 500"] = responseCode.code != 500;
    }
  });

  postman[Request]({
    name: "Add User",
    id: "65511998-9ab9-4152-9858-4c36e0af28bd",
    method: "POST",
    address: "{{url}}/addBorrower",
    data:
      '{\n\t"ssn":"E987648{{req}}",\n\t"name":"Name{{req}}",\n\t"address":"City{{req}}",\n\t"phone":"0000{{req}}"\n}',
    pre() {
      var count = pm.environment.get("req_count");
      if (!count) {
        count = 0;
      }
      if (count % 10 == 0) {
        pm.environment.set("req", count / 10);
      } else {
        pm.environment.set("req", 0);
      }
      pm.environment.set("req_count", count + 1);
    },
    post(response) {
      pm.test("Response time is less than 300ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(300);
      });
      tests["Status code is not 500"] = responseCode.code != 500;
    }
  });
}
